#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# commit message has to start with either "XXX-123:" or "NOJIRA:" or "Merge branch"
test "" = "$(head -1 "$1" | grep -vE '^([A-Z]+\-[0-9]+:|NOJIRA:|HOTFIX:|Merge branch).+')" || {
  echo >&2 'Aborting due to invalid commit message.'
  echo >&2 '--> Commit message needs to be prefixed by JIRA number.'
  echo >&2 '    e.g. "PBCD-345: blah" or "NOJIRA: blah" or "HOTFIX: blah"'
  echo >&2 '--> Rejected commit message is...'
  cat $1 | while read line; do
    [ `expr "$line" : "^#"` -gt 0 ] && break
    echo $line
  done
  exit 1
}
