#!/bin/sh

# Branch names to protect
PROTECTED_BRANCHES=( protect-from-force-push-test master deployment/qa deployment/production deployment/demo )

CURRENT_BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

PUSH_COMMAND=$(ps -ocommand= -p $PPID)

IS_DESTRUCTIVE='-f|--force|--delete'

WILL_REMOVE_PROTECTED_BRANCH=':'$PROTECTED_BRANCH

for i in "${PROTECTED_BRANCHES[@]}"
do

    PROTECTED_BRANCH=$i

    # エラーメッセージを定義
    MESSAGE="You CAN NOT '$PUSH_COMMAND' to '$PROTECTED_BRANCH'. You should 'git fetch && git merge origin $PROTECTED_BRANCH' first, then 'git push' without force option again."

    if [[ $PUSH_COMMAND =~ $IS_DESTRUCTIVE ]] && [ $CURRENT_BRANCH = $PROTECTED_BRANCH ]; then
      echo >&2 $MESSAGE
      exit 1
    fi

    if [[ $PUSH_COMMAND =~ $IS_DESTRUCTIVE ]] && [[ $PUSH_COMMAND =~ $PROTECTED_BRANCH ]]; then
      echo >&2 $MESSAGE
      exit 1
    fi

    if [[ $PUSH_COMMAND =~ $WILL_REMOVE_PROTECTED_BRANCH ]]; then
      echo >&2 $MESSAGE
      exit 1
    fi

done

exit 0
