#!/bin/sh
#The issue prefix to look for. This must be edited to match your project.
PROJECT_PREFIX=PBCD
ISSUE_PREFIX=$PROJECT_PREFIX-
#A separator which will be added after the issue is inserted. For readability.
COMMIT_TEXT_SEPARATOR=": "

#Check if it's a "fixup" or "squash" commit. If so we shouldn't alter anything.
FIRST_LINE=`head -n 1 "$1"`
if [[ x$FIRST_LINE == xfixup!* || x$FIRST_LINE == xsquash!* ]]
then
 exit
fi

BRANCH_NAME=`git symbolic-ref HEAD 2>/dev/null | cut -d"/" -f 3`
ISSUE_NAME=`echo $BRANCH_NAME | grep -o "${ISSUE_PREFIX}[0-9]*"`

if [[ x$ISSUE_NAME != x ]]
then
 #Prepend issue name
 sed -i -e "1i\\
  ${ISSUE_NAME}${COMMIT_TEXT_SEPARATOR}" "$1"
fi
